name: "Reusable: Node job"

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        default: '.'
      node-version:
        required: false
        default: '20'
      cache-dependency-path:
        required: false
        default: ''
      install:
        required: false
        default: 'true'
      run-lint:
        required: false
        default: 'true'
      run-typecheck:
        required: false
        default: 'true'
      run-build:
        required: false
        default: 'true'
      run-test:
        required: false
        default: 'true'
      tests-continue-on-error:
        required: false
        default: 'false'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.cache-dependency-path }}

      - name: Install dependencies
        if: ${{ inputs.install == 'true' }}
        run: |
          npm ci
        working-directory: ${{ inputs.working-directory }}

      - name: Run linter
        if: ${{ inputs['run-lint'] == 'true' }}
        run: |
          npm run lint
        working-directory: ${{ inputs.working-directory }}

      - name: Run TypeScript checks
        if: ${{ inputs.run-typecheck == 'true' }}
        run: |
          npx tsc --noEmit
        working-directory: ${{ inputs.working-directory }}

      - name: Build
        if: ${{ inputs['run-build'] == 'true' }}
        run: |
          npm run build
        working-directory: ${{ inputs.working-directory }}

      - name: Run tests
        if: ${{ inputs['run-test'] == 'true' }}
        env:
          NODE_OPTIONS: --experimental-fetch
        run: |
          npm test
        working-directory: ${{ inputs.working-directory }}
        continue-on-error: ${{ inputs['tests-continue-on-error'] == 'true' }}
