name: CI - SDK

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  sdk-build-test:
    name: Build & Test SDK
    uses: ./.github/workflows/reusable/node-workflow.yml
    with:
      working-directory: sdk/typescript
      node-version: '20'
      cache-dependency-path: sdk/typescript/package-lock.json
      install: 'true'
      run-lint: 'true'
      run-typecheck: 'true'
      run-build: 'true'
      run-test: 'true'
